export const NonTeachingStaffMembers = [
  {
    Name: "Sandip Kumar Mandal",
    Photo: require('../assets/NonTeachingStaff/nt_2.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "B. A.",
    DOB: "08/28/1971",
    Address: "Bara Sehara, P.O. - Chota Sehara, North 24 Prgs. Pin. 743442",
    Academics: "Calcutta University",
    Designation: "Head Clerk",
    Appointment: "07.12.05",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Bipul Kumar Saha",
    Photo: require('../assets/NonTeachingStaff/nt_3.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "Madhyamick",
    DOB: "03/11/1962",
    Address: "15/H/41, Narkeldanga North Road. Kolkata - 11",
    Academics: "West Bengal Board of Secondary Education",
    Designation: "Clerk",
    Appointment: "07.12.05",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Uttam Kumar Saha",
    Photo: require('../assets/NonTeachingStaff/nt_4.png'),
    AppointmentNature: "PERMANENT",
    Qualification: "B. Com.",
    DOB: "05/18/1962",
    Address:"H-3, L.I.G. Houshing Estate, 8/1, Rustomji Parshi Road., Cossipur Udaynbati, Kolkata - 2",
    Academics: "Calcutta University",
    Designation: "Cashier",
    Appointment: "29.07.06",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Anil Mallick",
    Photo: require('../assets/NonTeachingStaff/nt_5.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "VIII Passed",
    DOB: "01/25/1975",
    Address: "2, Dhapa Road, New Mallick Basti, South 24 Prgs. Pin - 700 115",
    Academics: "",
    Designation: "Dom",
    Appointment: "07.12.05",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Kartick Chandra Mondal",
    Photo: require('../assets/NonTeachingStaff/nt_6.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "B. Com.",
    DOB: "09/30/1981",
    Address: "64, Dhan Devi Khanna Road. Kolkata - 700 054",
    Academics: "Calcutta University",
    Designation: "Accountant",
    Appointment: "23.11.11",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Uday Sankar Saha",
    Photo: require('../assets/NonTeachingStaff/nt_7.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "S.F.",
    DOB: "12/07/1976",
    Address:
      "Purba Bidhan Pally (Ichapur), P.O. - Nawabganj, P.S. - Nawapara, North 24 Prgs. Pin - 743144",
    Academics: "West Bengal Board of Secondary Education",
    Designation: "",
    Appointment: "23.11.11",
    Department: "Hospital",
    Remarks: "",
  },
  {
    Name: "Prabir Adhikary",
    Photo: require('../assets/NonTeachingStaff/nt_8.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "H.S.",
    DOB: "",
    Address: "106/E, Narkeldanga North Road. Kolkata - 11",
    Academics: "WBCHSE",
    Designation: "Lab.\n Technician",
    Appointment: "02.01.14",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Lachman Das",
    Photo: require('../assets/NonTeachingStaff/nt_9.png'),
    AppointmentNature: "PERMANENT",
    Qualification: "Literate",
    DOB: "02/12/1960",
    Address:"Kakurja - D, Naitand, Big Post - Suria, Gridi, Jharkhand - 825320",
    Academics: "",
    Designation: "Sweeper",
    Appointment: "27.03.79",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Raju Mahato",
    Photo: require('../assets/NonTeachingStaff/nt_10.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "H.S.",
    DOB: "12/25/1976",
    Address: "63/1, Mahesh Barik Lane. Kolkata - 11",
    Academics: "West Bengal Higher Secondary Board of Council",
    Designation: "Lab. Attendant",
    Appointment: "01.06.01",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Debabrata Patra",
    Photo: require('../assets/NonTeachingStaff/nt_11.jpg'),
    AppointmentNature: "PERMANENT",
    Qualification: "MLIS",
    DOB: "21.10.90",
    Address:"V - Bhatia, P - Lakshi Pari, P.S. - Pingla, Dist. Paschim Medinipur\n 721 155",
    Academics: "Calcutta university",
    Designation: "Librarian",
    Appointment: "22.04.19",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Subhadeep Sengupta",
    Photo: require('../assets/avatar.jpg'),
    AppointmentNature: "CONTRACTUAL\n REGULAR",
    Qualification: "Madhyamick",
    DOB: "05/08/1986",
    Address: "Tallagicha Rathtala, Kharogpur, West Midnapur, 721 306",
    Academics: "West Bengal Board of Secondary Education",
    Designation: "Lab Attendent\n ANATOMY",
    Appointment: "13.04.21",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Atanu Biswas",
    Photo: require('../assets/avatar.jpg'),
    AppointmentNature: "CONTRACTUAL\n REGULAR",
    Qualification: "H.S.",
    DOB: "11/21/1991",
    Address: "V- Argora, PO - Ghatal, Dist. Paschim Midnapur, 721 212",
    Academics: "West Bengal Higher Secondary Board of Council",
    Designation: "Lab. Attendent\n PATHOLOGY",
    Appointment: "13.04.21",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Mr. Sibas Das",
    Photo: require('../assets/avatar.jpg'),
    AppointmentNature: "CONTRACTUAL\n REGULAR",
    Qualification: "Madhyamick",
    DOB: "04/11/1992",
    Address: "V- Argora, PO - Ghatal, Dist. Paschim Midnapur, 721 212",
    Academics: "West Bengal Board of Secondary Education",
    Designation: "Lab. Attendent\n Physiology",
    Appointment: "13.04.21",
    Department: "College",
    Remarks: "",
  },
  {
    Name: "Mr.S. K. Sinha Chowdhury",
    Photo: require('../assets/avatar.jpg'),
    AppointmentNature: "CONTRACTUAL",
    Qualification: "C.A.",
    DOB: "",
    Address: "",
    Academics: "",
    Designation: "Auditor",
    Appointment: "",
    Department: "College / Hospital",
    Remarks: "",
  },
  {
    Name: "Tanmoy Bag",
    Photo: require('../assets/avatar.jpg'),
    AppointmentNature: "CONTRACTUAL\n REGULAR",
    Qualification: "H.S.",
    DOB: "",
    Address: "MALANCHA ROAD, KHARAGPUR, 712304",
    Academics: "West Bengal Higher Secondary Board of Council",
    Designation: "LIBRARY\n ASST.",
    Appointment: "01/06/2022",
    Department: "COLLEGE",
    Remarks: "",
  },
];

export const NonTeachingStaffKey = [
  { key: "Name", label: "Name of \n the Employee" },
  { key: "AppointmentNature", label: "Nature of Appointment" },
  { key: "Qualification", label: "Qualification" },
  { key: "DOB", label: "Date of\n Birth" },
  { key: "Address", label: "Residential Address" },
  { key: "Academics", label: "Passing Academic Organization /University" },
  { key: "Designation", label: "Designation" },
  { key: "Appointment", label: "Joining of Appointment" },
  { key: "Department", label: "Department" },
];
