export const TeachingStaffMembers = [
  {
    Name: "Dr. Bidhu Bhusan Jana",
    Photo: require("../assets/TeachingStaff/b2_1.jpg"),
    Designation: "Adminstrator",
    DepartmentJoiningDate: "Anatomy",
    Time: "Full Time",
    Qualification: "B.A.; D.M.S. (Cal); B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority:
      "B.A. - C.U; D.M.S. - C.H.M.(WB); B.H.M.S. & M.D. - Bihar University",
    DOB: "07.01.1955",
    RegdDetails: "3437 - 24/04/1976; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "38 yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Nidan Betal",
    Photo: require("../assets/TeachingStaff/b3_1.jpg"),
    Designation: "PRINCIPAL & H.O.D",
    DepartmentJoiningDate: "Materia Medica; 02/05/1991",
    Time: "Full Time",
    Qualification: "D.M.S. (Cal); B.H.M.S. (Gr.); M.D. (Hom.)",
    AwardingAuthority:
      "D.M.S. - C.H.M.(WB); B.H.M.S. (Gr.) - B.F.U.H.S.(Punjab); M.D. (Hom.) - Dr. B.R.A. University(Agra)",
    DOB: "07.10.1959",
    RegdDetails: "9525 - 23/06/1985; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "32 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Prof. (Dr.) Deb Kumar Das",
    Photo: require("../assets/avatar.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Anatomy; 01/07/2023",
    Time: "FULL TIME; (CONTRACTUAL)",
    Qualification: "DMS; M.D. (Hom.)",
    AwardingAuthority: "C.H.M. W.B.; DR. B.R.AMBEDKAR UNIVERSITY",
    DOB: "01/01/1961",
    RegdDetails: "14124- (C.H.M.W.B.); COUNCIL OF HOM. MED. W.B.",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Supriya Halder",
    Photo: require("../assets/TeachingStaff/b5_1.jpg"),
    Designation: "LECTURER / Asst. Professor",
    DepartmentJoiningDate: "ANATOMY; 08/04/2022",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "WBUHS; WBUHS",
    DOB: "06/13/1992",
    RegdDetails: "31352 - 27/01/2017; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "8months",
    Remarks: "",
  },
  {
    Name: "Dr. Amitava Dhar",
    Photo: require("../assets/TeachingStaff/b6_1.jpg"),
    Designation: "Professor & H.O.D. , Retired - NOV 2023",
    DepartmentJoiningDate: "Community Medicine; 01/02/1987",
    Time: "Full Time",
    Qualification: "D.M.S. (Cal); C.A.H.",
    AwardingAuthority: "D.M.S. - C.H.M.(WB)",
    DOB: "08.11.1958",
    RegdDetails: "8394 - 10/12/1981; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "36 Yrs. +",
    Remarks: "RETIRED - 30/11/2023",
  },
  {
    Name: "Dr. Deb Kumar Palit",
    Photo: require("../assets/TeachingStaff/b7_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "Community Medicine; 28/02/2019",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "BHMS - WBUHS; M.D. (Hom.) - WBUHS",
    DOB: "22.05.1982",
    RegdDetails: "30444 - 16.12.2013; Council of Homoeopathic Medicine, W.B.",
    RegdExp: "3 yrs",
    Remarks: "",
  },
  {
    Name: "Dr. Gargi Kundu",
    Photo: require("../assets/TeachingStaff/b8_1.jpg"),
    Designation: "Associate Professor & H.O.D.",
    DepartmentJoiningDate: "F.M.T.; 14/12/2007",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. - C.U.",
    DOB: "28.04.1975",
    RegdDetails: "23039 - 12/06/2000; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "15 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Arunavo Nath",
    Photo: require("../assets/TeachingStaff/b9_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "F. M. T.; 28/02/2019",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. (Hom.) - (W.B.U.H.S.)",
    DOB: "03.01.1980",
    RegdDetails: "27296 - 24.07.2008; Council of Homoeopathic Medicine, W.B.",
    RegdExp: "3 YRS.+",
    Remarks: "",
  },
  {
    Name: "Dr. Asish Kr. Sasmal",
    Photo: require("../assets/TeachingStaff/b10_1.jpg"),
    Designation: "Associate Professor",
    DepartmentJoiningDate: "Materia Medica; 02/11/2011",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. - W.B.U.H.S.",
    DOB: "20.10.1978",
    RegdDetails: "26112 - 07/03/2006; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "11 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Henna Khanam",
    Photo: require("../assets/TeachingStaff/b11_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "MATERIA MEDICA; 08/04/2022",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "WBUHS; WBUHS",
    DOB: "02/28/1991",
    RegdDetails: "31501 - 03/02/2017;  ; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "8 mnth. at PCMHH & C",
    Remarks: "",
  },
  {
    Name: "Dr. Sukhendu Sarkar",
    Photo: require("../assets/TeachingStaff/b12_1.jpg"),
    Designation: "Associate Professor & H.O.D.",
    DepartmentJoiningDate: "Organon of Medicine; 11/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. - W.B.U.H.S.",
    DOB: "30.11.1971",
    RegdDetails: "23265 - 20/11/2000; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "9 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Nivedita Kundu",
    Photo: require("../assets/TeachingStaff/b13_1.jpg"),
    Designation: "Lecturer / Asst. Professor, Resigned - JULY 2023",
    DepartmentJoiningDate: "Organon of Med.; 28/02/2019",
    Time: "Full Time",
    Qualification: "BHMS; MD (HOM)",
    AwardingAuthority: "BHMS - WBUHS; WBUHS",
    DOB: "27.11.1989",
    RegdDetails: "30820; Council of Homoeopathic Medicine, W.B.",
    RegdExp: "3 Yrs.",
    Remarks: "RESIGNED - JULY 2023",
  },
  {
    Name: "Dr. PRITHA HALDER",
    Photo: require("../assets/TeachingStaff/b14_1.png"),
    Designation: "Lecturer / Asst. Professor, Resigned - JULY 2023",
    DepartmentJoiningDate: "PATHOLOGY; 14/11/2019",
    Time: "Full Time",
    Qualification: "BHMS; MD (Hom.)",
    AwardingAuthority: "(WBUHS); (WBUHS)",
    DOB: "01/27/1990",
    RegdDetails: "30694 - 13/11/2014; Council of Homoeopathic Medicine, W.B.",
    RegdExp: "3 Yrs.",
    Remarks: "RESIGNED - JULY 2023",
  },
  {
    Name: "Prof. (Dr.) BISWAJYOTI; CHATTERJEE",
    Photo: require("../assets/TeachingStaff/b15_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "PATHOLOGY; 16/08/2022",
    Time: "FULL TIME (CONTRACTUAL)",
    Qualification: "DMS; MD (Hom.); Dip. MLT",
    AwardingAuthority:
      "C. H. M.(W. B.);  DEEMED, UNIVERSITY, UDAIPUR;  M.L.T.I. KERALA",
    DOB: "06/16/1962",
    RegdDetails: "10244 - 18/07/1984; Council of Homoeopathic Medicine, W.B.",
    RegdExp: "36Yrs+ Bengal Homoeopathic Medical College & Hospital; Asansol,",
    Remarks: "",
  },
  {
    Name: "Dr. Ambika Kundu",
    Photo: require("../assets/TeachingStaff/b16_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "Pharmacy; 13/11/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. - W.B.U.H.S.",
    DOB: "18.05.1978",
    RegdDetails: "25061 - 2003; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "9Yrs.",
    Remarks: "",
  },
  {
    Name: "Dr. Anindita Das",
    Photo: require("../assets/TeachingStaff/b17_1.jpg"),
    Designation: "LECTURER",
    DepartmentJoiningDate: "Pharmacy; 11/04/2023",
    Time: "PROBATIONAL",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - WBUHS; M.D.(Hom.) - RGUHS",
    DOB: "13/05/1991",
    RegdDetails: "31779; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Raghu Nath Dhara",
    Photo: require("../assets/TeachingStaff/b18_1.jpg"),
    Designation: "PROFESSOR & H.O.D",
    DepartmentJoiningDate: "Physiology; 20/12/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority:
      "B.Sc. (C.U.); D.M.S. (Cal); B.H.M.S. (Gr.); M.D. (Hom.)",
    DOB: "25.07.1961",
    RegdDetails: "11412; COUNCIL OF HOM. MED. W.B.",
    RegdExp:
      "2001 - 13, at BVHMC & Hospital, Sainthia as Associate Prof. & H.O.D.;  ; 9 Yrs. + at PCMHH&C; Permanent Faculty Now as H.O.D +Professor.",
    Remarks: "",
  },
  {
    Name: "Dr. Sneha Kariwala (Agarwal)",
    Photo: require("../assets/TeachingStaff/b19_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "Physiology; 02/03/2019",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "BHMS - W.B.U.H.S.; D.U",
    DOB: "08.09.1987",
    RegdDetails: "30205 - 21.05.2013; Council of Homoeopathic Medicine, W.B.",
    RegdExp: "3 Yrs",
    Remarks: "",
  },
  {
    Name: "Dr. Santanu Ghosh",
    Photo: require("../assets/TeachingStaff/b20_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Practice of Medicine; 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. (Hom.) - Agra University",
    DOB: "01.02.1972",
    RegdDetails: "22658 - 01/12/1999;  ; COUNCIL OF HOM. MEDICINE, W.B.",
    RegdExp:"6 Yrs. NCCHMC&H as GUEST TEACHER, DEPT. OF PRACTICE OF MEDICINE;  ; 9 Yrs. + at PCMHH&C; Permanent Faculty Now as H.O.D +Professor.",
    Remarks: "",
  },
  {
    Name: "Dr. BISWAJIT BERA",
    Photo: require("../assets/TeachingStaff/b21_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "PRACTICE OF MEDICINE; 12/04/2022",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "WBUHS; WBUHS",
    DOB: "02/02/1991",
    RegdDetails: "31701 - 03/11/2017;  ; COUNCIL OF HOM. MEDICINE, W.B.",
    RegdExp: "8 mnths.",
    Remarks: "",
  },
  {
    Name: "Dr. Sushanta Sasmal",
    Photo: require("../assets/TeachingStaff/b22_1.jpg"),
    Designation: "LECTURER",
    DepartmentJoiningDate: "Repertory; 04/04/2023",
    Time: "PROBATIONAL",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - WBUHS; M.D. - WBUHS",
    DOB: "06/04/1993",
    RegdDetails: "31924 - 06/04/1993; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Arijit Pal Choudhury",
    Photo: require("../assets/TeachingStaff/b23_1.jpg"),
    Designation: "Reader",
    DepartmentJoiningDate: "Gynae. & Obs.; 05/06/2023",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.; M.D.(Hom.)",
    AwardingAuthority: "C.U.; C.U.",
    DOB: "26/01/1968",
    RegdDetails: "20120; COUNCIL OF HOM. MEDICINE, W.B.",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Dipak Kar",
    Photo: require("../assets/TeachingStaff/b24_1.jpg"),
    Designation: "Lecturer / Asst. Professor",
    DepartmentJoiningDate: "Surgery; 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. (Hom.)- JRNRV",
    DOB: "18.03.1970",
    RegdDetails: "20402 - 06/02/1996; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "9 Yrs",
    Remarks: "",
  },
  {
    Name: "Dr. Debabrata Kundu",
    Photo: require("../assets/TeachingStaff/b25_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Surgery; 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.; M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.; M.D. (Hom.) - C.U",
    DOB: "09.01.1970",
    RegdDetails: "20388 - 05/02/1996; COUNCIL OF HOM. MED. W.B.",
    RegdExp: "9 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Prabir Kumar Sen",
    Photo: require("../assets/TeachingStaff/b26_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Anatomy; 28/02/2019",
    Time: "Guest Faculty",
    Qualification: "MBBS; MS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Anantadeb Chattopadhyay",
    Photo: require("../assets/TeachingStaff/b27_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Organon of Medicine; 18/04/2016",
    Time: "Guest Faculty",
    Qualification: "B.Sc, DMS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. L. B. Mondal",
    Photo: require("../assets/TeachingStaff/b28_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Organon of Medicine; 27/11/2015",
    Time: "Guest Faculty",
    Qualification: "BHMS; MD (Hom.)",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  // {
  //   Name: "Dr. Alok Das",
  //   Photo: require("../assets/TeachingStaff/b29_1.jpg"),
  //   Designation: "Hon. Guest Lecturer",
  //   DepartmentJoiningDate: "Gynae. & Obs.; 11/05/2013",
  //   Time: "Guest Faculty",
  //   Qualification: "BHMS; MD (Hom.)",
  //   AwardingAuthority: "",
  //   DOB: "",
  //   RegdDetails: "",
  //   RegdExp: "",
  //   Remarks: "",
  // },
  {
    Name: "Dr. K. K. Chatterjee",
    Photo: require("../assets/TeachingStaff/b30_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Surgery (Eye); 19/08/2006",
    Time: "Guest Faculty",
    Qualification: "MBBS; DOMS; MS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Gopal Dave",
    Photo: require("../assets/TeachingStaff/b31_1.jpg"),
    Designation: "Hon. Guest Professor, Passed Away",
    DepartmentJoiningDate: "Surgery - General; 24/04/2004",
    Time: "Guest Faculty",
    Qualification: "MBBS; MS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "DIED",
  },
  {
    Name: "Dr. T. K. Palit",
    Photo: require("../assets/TeachingStaff/b32_1.jpg"),
    Designation: "Hon. Guest Professor, Passed Away",
    DepartmentJoiningDate: "Surgery - ENT; 06/04/1998",
    Time: "Guest Faculty",
    Qualification: "MBBS; DLO",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "DIED",
  },
  {
    Name: "Dr. Manindra Kumar Biswas",
    Photo: require("../assets/avatar.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Pr. of Medicine",
    Time: "Guest Faculty",
    Qualification: "MBBS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Dr. Abhijit Sharma",
    Photo: require("../assets/avatar.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Surgery - General; 14/08/2023",
    Time: "Guest Faculty",
    Qualification: "MBBS(Hons); M.R.C.S.(England. Edin. Ireland)",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Mr. Karuna Sindhu Jana",
    Photo: require("../assets/avatar.jpg"),
    Designation: "Hon. Psychologist",
    DepartmentJoiningDate: "Organon of Medicine - Psychology; 24/09/2023",
    Time: "Guest Faculty",
    Qualification: "M.PHIL(Clinical Psychology)",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  },
  {
    Name: "Mrs. Joyti Verma",
    Photo: require("../assets/avatar.jpg"),
    Designation: "Yoga Expert",
    DepartmentJoiningDate: "Yoga ; 25/08/2022",
    Time: "Part Time",
    Qualification: "M.A. (Yoga)",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    RegdExp: "",
    Remarks: "",
  }
];

export const TeachingStaffKey = [
  { key: "Name", label: "Name" },
  { key: "Designation", label: "Designation" },
  { key: "DepartmentJoiningDate", label: "Department & JOINING DATE" },
  { key: "Time", label: "Full /Part Time" },
  { key: "Qualification", label: "Qualification" },
  { key: "AwardingAuthority", label: "Awarding Authority with year of Award" },
  { key: "DOB", label: "Date of Birth" },
  {
    key: "RegdDetails",
    label: "Regd No & Date of Regd with Name of Council / Board",
  },
  {
    key: "RegdExp",
    label:
      " Regd Experience in each Teaching Cadre & duration & Name of the Institute",
  },
];
