export const TeachingStaffMembers = [
  {
    Name: "Dr. Bidhu Bhusan Jana",
    Photo: require("../assets/TeachingStaff/b2_1.jpg"),
    Designation: "Adminstrator",
    DepartmentJoiningDate: "Anatomy",
    Time: "Full Time",
    Qualification: "B.A., D.M.S. (Cal), B.H.M.S., M.D. (Hom.)",
    AwardingAuthority:
      "B.A. - C.U\n D.M.S. - C.H.M.WB\n B.H.M.S. & M.D. - Bihar University",
    DOB: "07.01.1955",
    RegdDetails: "Anatomy\n (3437) - 24/04/1976",
    RegdExp: "38 yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Nidan Betal",
    Photo: require("../assets/TeachingStaff/b3_1.jpg"),
    Designation: "PRINCIPAL & H.O.D",
    DepartmentJoiningDate: "Materia Medica\n 02/05/1991",
    Time: "Full Time",
    Qualification: "D.M.S. (Cal)\n B.H.M.S. (Gr.) ,\n M.D. (Hom.)",
    AwardingAuthority:
      "D.M.S. - C.H.M.WB\n B.H.M.S. (Gr.) - B.F.U.H.S., Punjab\n M.D. (Hom.) - Dr. B.R.A. University, Agra",
    DOB: "07.10.1959",
    RegdDetails: "Materia Medica\n (9525) - 23/06/1985",
    " RegdExp": "32 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Prof. (Dr.)\n GOUTAM ASH",
    Photo: require("../assets/TeachingStaff/b4_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Anatomy\n 11/04/2022",
    Time: "FULL TIME\n (CONTRACTUAL)",
    Qualification: "BHMS\n  \n M.D. (Hom.)",
    AwardingAuthority: "C.U.\n  \n  \n DR. B.R.AMBEDKAR UNIVERSITY",
    DOB: "12/03/1959",
    RegdDetails: "10764\n 04/11/1985\n  \n COUNCIL OF HOM. MED. W.B.",
    " RegdExp": "38 Yrs +",
    Remarks: "",
  },
  {
    Name: "Dr. Supriya Halder",
    Photo: require("../assets/TeachingStaff/b5_1.jpg"),
    Designation: "LECTURER /\n Asst. Professor",
    DepartmentJoiningDate: "ANATOMY\n 08/04/2022",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.\n  \n M.D. (Hom.)",
    AwardingAuthority: "D.N.DE. (WBUHS)\n  \n  \n MAHESH (WBUHS)",
    DOB: "06/13/1992",
    RegdDetails: "31352\n 27/01/2017\n  \n COUNCIL OF HOM. MED. W.B.",
    " RegdExp": "8months",
    Remarks: "",
  },
  {
    Name: "Dr. Amitava Dhar",
    Photo: require("../assets/TeachingStaff/b6_1.jpg"),
    Designation: "Professor & H.O.D.",
    DepartmentJoiningDate: "Community Medicine\n 01/02/1987",
    Time: "Full Time",
    Qualification: "D.M.S. (Cal)\n C.A.H.",
    AwardingAuthority: "D.M.S. - C.H.M.WB",
    DOB: "08.11.1958",
    RegdDetails: "Community Medicine\n (8394) - 10/12/1981",
    " RegdExp": "36 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Deb Kumar Palit",
    Photo: require("../assets/TeachingStaff/b7_1.jpg"),
    Designation: "Lecturer /\n Asst. Professor",
    DepartmentJoiningDate: "Community Medicine\n 28/02/2019",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n  \n M.D. (Hom.)",
    AwardingAuthority: "BHMS - PCMHHC\n (WBUHS)\n  \n NIH - WBUHS",
    DOB: "22.05.1982",
    RegdDetails: "30444\n 16.12.2013\n Council of Homoeopathic Medicine, W.B.",
    " RegdExp": "3 yrs",
    Remarks: "",
  },
  {
    Name: "Dr. Gargi Kundu",
    Photo: require("../assets/TeachingStaff/b8_1.jpg"),
    Designation: "Associate Professor & H.O.D.",
    DepartmentJoiningDate: "F.M.T.\n 14/12/2007",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. - C.U.",
    DOB: "28.04.1975",
    RegdDetails: "F.M.T.\n (23039) - 12/06/2000",
    " RegdExp": "15 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Arunavo Nath",
    Photo: require("../assets/TeachingStaff/b9_1.jpg"),
    Designation: "Lecturer /\n Asst. Professor",
    DepartmentJoiningDate: "F. M. T.\n 28/02/2019",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority:
      "B.H.M.S. - CHMC (C.U.)\n  \n M.D. (Hom.) (NIH)\n (W.B.U.H.S.)",
    DOB: "03.01.1980",
    RegdDetails: "27296\n 24.07.2008\n Council of Homoeopathic Medicine, W.B.",
    " RegdExp": "3 YRS.+",
    Remarks: "",
  },
  {
    Name: "Dr. Asish Kr. Sasmal",
    Photo: require("../assets/TeachingStaff/b10_1.jpg"),
    Designation: "Associate Professor",
    DepartmentJoiningDate: "Materia Medica\n 02/11/2011",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. - W.B.U.H.S.",
    DOB: "20.10.1978",
    RegdDetails: "Materia Medica\n (26112) - 07/03/2006",
    " RegdExp": "11 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Henna Khanam",
    Photo: require("../assets/TeachingStaff/b11_1.jpg"),
    Designation: "LECTURER /\n Asst. Professor",
    DepartmentJoiningDate: "MATERIA MEDICA\n 08/04/2022",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.\n  \n M.D. (Hom.)",
    AwardingAuthority: "(WBUHS) PCMHH & C\n  \n MAHESH BHATT.\n (WBUHS)",
    DOB: "02/28/1991",
    RegdDetails: "31501\n 03/02/2017\n  \n COUNCIL OF HOM. MED. W.B.",
    " RegdExp": "8 mnth. at PCMHH & C",
    Remarks: "",
  },
  {
    Name: "Dr. Sukhendu Sarkar",
    Photo: require("../assets/TeachingStaff/b12_1.jpg"),
    Designation: "Associate Professor & H.O.D.",
    DepartmentJoiningDate: "Organon of Medicine\n 11/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. - W.B.U.H.S.",
    DOB: "30.11.1971",
    RegdDetails: "Organon of Medicine\n 23265 - 20/11/2000",
    " RegdExp": "9 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Nivedita Kundu",
    Photo: require("../assets/TeachingStaff/b13_1.jpg"),
    Designation: "Lecturer /\n Asst. Professor",
    DepartmentJoiningDate: "Organon of Med.\n 28/02/2019",
    Time: "Full Time",
    Qualification: "BHMS\n  \n  \n MD (HOM)",
    AwardingAuthority: "BHMS - PCMHHC\n (WBUHS)\n  \n NIH, WBUHS",
    DOB: "27.11.1989",
    RegdDetails: "30820\n Council of Homoeopathic Medicine, W.B.",
    " RegdExp": "3 Yrs.",
    Remarks: "",
  },
  {
    Name: "Dr. PRITHA HALDER",
    Photo: require("../assets/TeachingStaff/b14_1.png"),
    Designation: "LECTURER /\n Asst. Professor",
    DepartmentJoiningDate: "PATHOLOGY\n 14/11/2019",
    Time: "Full Time",
    Qualification: "BHMS\n  \n MD (Hom.)",
    AwardingAuthority: "(WBUHS)\n  \n  \n (WBUHS)",
    DOB: "01/27/1990",
    RegdDetails: "30694\n 13/11/2014\n Council of Homoeopathic Medicine, W.B.",
    " RegdExp": "3 Yrs.",
    Remarks: "",
  },
  {
    Name: "Prof. (Dr.) BISWAJYOTI\n CHATTERJEE",
    Photo: require("../assets/TeachingStaff/b15_1.jpg"),
    Designation: "PROFESSOR\n & H.O.D.",
    DepartmentJoiningDate: "PATHOLOGY\n 16/08/2022",
    Time: "FULL TIME (CONTRACTUAL)",
    Qualification: "DMS,\n  \n MD (Hom.)\n  \n  \n Dip. MLT",
    AwardingAuthority:
      "(C. H. M. W. B..)\n  \n (DEEMED, UNIVERSITY, UDAIPUR)\n  \n (M.L.T.I. KERALA)",
    DOB: "06/16/1962",
    RegdDetails: "10244\n 18/07/1984\n Council of Homoeopathic Medicine, W.B.",
    " RegdExp":
      "36Yrs+ Bengal Homoeopathic Medical College & Hospital\n Asansol,",
    Remarks: "",
  },
  {
    Name: "Dr. Ambika Kundu",
    Photo: require("../assets/TeachingStaff/b16_1.jpg"),
    Designation: "Lecturer /\n Asst. Professor",
    DepartmentJoiningDate: "Pharmacy\n 13/11/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority:
      "B.H.M.S. - C.U.\n M.D. - W.B.U.H.S.\n (M.B.H.M.C. & H.)",
    DOB: "18.05.1978",
    RegdDetails: "Pharmacy\n 25061 - (2003)",
    " RegdExp": "9Yrs.",
    Remarks: "",
  },
  {
    Name: "Dr. Mustafizur Rahaman",
    Photo: require("../assets/TeachingStaff/b17_1.jpg"),
    Designation: "Associate Professor & H.O.D.",
    DepartmentJoiningDate: "Pharmacy\n 13/11/2012",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "D.H.M.S. (W.C.H.M.) M.D. (Hom.) (BBAU)",
    DOB: "04.02.1966",
    RegdDetails: "Pharmacy\n 19552 - (2009)",
    " RegdExp": "10 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Raghu Nath Dhara",
    Photo: require("../assets/TeachingStaff/b18_1.jpg"),
    Designation: "PROFESSOR\n & H.O.D",
    DepartmentJoiningDate: "Physiology\n 20/12/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority:
      "B.Sc. (C.U.),\n D.M.S. (Cal),\n B.H.M.S. (Gr.)\n M.D. (Hom.)",
    DOB: "25.07.1961",
    RegdDetails: "COUNCIL OF HOM. MEDICINE, W.B.\n  \n 11412",
    " RegdExp":
      "2001 - 13, at BVHMC & Hospital, Sainthia as Associate Prof. & H.O.D.\n  \n 9 Yrs. + at PCMHH&C\n Permanent Faculty Now as H.O.D +Professor.",
    Remarks: "",
  },
  {
    Name: "Dr. Sneha Kariwala (Agarwal)",
    Photo: require("../assets/TeachingStaff/b19_1.jpg"),
    Designation: "Lecturer /\n Asst. Professor",
    DepartmentJoiningDate: "Physiology\n 02/03/2019",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n  \n  \n M.D. (Hom.)",
    AwardingAuthority: "BHMS\n (NIH)\n (W.B.U.H.S.)\n  \n (NHMCH)\n (D.U)",
    DOB: "08.09.1987",
    RegdDetails: "30205\n 21.05.2013\n Council of Homoeopathic Medicine, W.B.",
    " RegdExp": "3 Yrs",
    Remarks: "",
  },
  {
    Name: "Dr. Santanu Ghosh",
    Photo: require("../assets/TeachingStaff/b20_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Practice of Medicine\n 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. (Hom.) - Agra University",
    DOB: "01.02.1972",
    RegdDetails: "22658\n 01/12/1999\n  \n COUNCIL OF HOM. MEDICINE, W.B.",
    " RegdExp":
      "6 Yrs. NCCHMC&H as GUEST TEACHER, DEPT. OF PRACTICE OF MEDICINE\n  \n 9 Yrs. + at PCMHH&C\n Permanent Faculty Now as H.O.D +Professor.",
    Remarks: "",
  },
  {
    Name: "Dr. BISWAJIT BERA",
    Photo: require("../assets/TeachingStaff/b21_1.jpg"),
    Designation: "LECTURER /\n Asst. Professor",
    DepartmentJoiningDate: "PRACTICE OF MEDICINE\n 12/04/2022",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "(WBUHS)\n (WBUHS)",
    DOB: "02/02/1991",
    RegdDetails: "31701\n 03/11/2017\n  \n COUNCIL OF HOM. MEDICINE, W.B.",
    " RegdExp": "8 mnths.",
    Remarks: "",
  },
  {
    Name: "Dr. Sabyasachi Biswas",
    Photo: require("../assets/TeachingStaff/b22_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Repertory\n 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. - C.U.",
    DOB: "05.05.1970",
    RegdDetails: "COUNCIL OF HOM. MEDICINE, W.B.\n  \n 21446\n 20/02/1998",
    " RegdExp": "9 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. SANA SHAHID",
    Photo: require("../assets/avatar.jpg"),
    Designation: "LECTURER /\n Asst. Professor",
    DepartmentJoiningDate: "REPERTORY\n 19/07/2021",
    Time: "FULL TIME",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "(WBUHS)\n (WBUHS)",
    DOB: "03/15/1991",
    RegdDetails: "31040\n 19/01/2016\n  \n COUNCIL OF HOM. MEDICINE, W.B.",
    " RegdExp": "",
    Remarks: "Resigned",
  },
  {
    Name: "Dr. Dipak Kar",
    Photo: require("../assets/TeachingStaff/b24_1.jpg"),
    Designation: "Lecturer/\n Asst. Professor",
    DepartmentJoiningDate: "Surgery\n 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. (Hom.)- JRNRV",
    DOB: "18.03.1970",
    RegdDetails: "Surgery\n 20402\n 06/02/1996",
    " RegdExp": "9 Yrs",
    Remarks: "",
  },
  {
    Name: "Dr. Debabrata Kundu",
    Photo: require("../assets/TeachingStaff/b25_1.jpg"),
    Designation: "PROFESSOR & H.O.D.",
    DepartmentJoiningDate: "Surgery\n 02/05/2013",
    Time: "Full Time",
    Qualification: "B.H.M.S.\n M.D. (Hom.)",
    AwardingAuthority: "B.H.M.S. - C.U.\n M.D. - C.U",
    DOB: "09.01.1970",
    RegdDetails: "COUNCIL OF HOM. MEDICINE, W.B.\n 20388\n 05/02/1996",
    " RegdExp": "9 Yrs. +",
    Remarks: "",
  },
  {
    Name: "Dr. Prabir Kumar Sen",
    Photo: require("../assets/TeachingStaff/b26_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Anatomy\n 28/02/2019",
    Time: "Guest Faculty",
    Qualification: "MBBS, MS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. Anantadeb Chattopadhyay",
    Photo: require("../assets/TeachingStaff/b27_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Organon of Medicine\n 18/04/2016",
    Time: "Guest Faculty",
    Qualification: "B.Sc, DMS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. L. B. Mondal",
    Photo: require("../assets/TeachingStaff/b28_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Organon of Medicine\n 27/11/2015",
    Time: "Guest Faculty",
    Qualification: "BHMS,\n MD (Hom.)",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. Alok Das",
    Photo: require("../assets/TeachingStaff/b29_1.jpg"),
    Designation: "Hon. Guest Lecturer",
    DepartmentJoiningDate: "Gynae. & Obs.\n 11/05/2013",
    Time: "Guest Faculty",
    Qualification: "BHMS,\n MD (Hom.)",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. K. K. Chatterjee",
    Photo: require("../assets/TeachingStaff/b30_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Surgery (Eye)\n 19/08/2006",
    Time: "Guest Faculty",
    Qualification: "MBBS, DOMS, MS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. Gopal Dave",
    Photo: require("../assets/TeachingStaff/b31_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Surgery - General\n 24/04/2004",
    Time: "Guest Faculty",
    Qualification: "MBBS, MS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. T. K. Palit",
    Photo: require("../assets/TeachingStaff/b32_1.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Surgery - ENT\n 06/04/1998",
    Time: "Guest Faculty",
    Qualification: "MBBS, DLO",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
  {
    Name: "Dr. Manindra Kumar Biswas",
    Photo: require("../assets/avatar.jpg"),
    Designation: "Hon. Guest Professor",
    DepartmentJoiningDate: "Pr. of Medicine",
    Time: "Guest Faculty",
    Qualification: "MBBS",
    AwardingAuthority: "",
    DOB: "",
    RegdDetails: "",
    " RegdExp": "",
    Remarks: "",
  },
];

export const TeachingStaffKey = [
  { key: "Name", label: "Name" },
  { key: "Designation", label: "Designation" },
  { key: "DepartmentJoiningDate", label: "Department & JOINING DATE" },
  { key: "Time", label: "Full /Part Time" },
  { key: "Qualification", label: "Qualification" },
  { key: "AwardingAuthority", label: "Awarding Authority with year of Award" },
  { key: "DOB", label: "Date of Birth" },
  {
    key: "RegdDetails",
    label: "Regd No & Date of Regd with Name of Council / Board",
  },
  {
    key: "RegdExp",
    label:
      " Regd Experience in each Teaching Cadre & duration & Name of the Institute",
  },
];
